### ISSUE TITLE
Publish v1.0.2 to npm

### ISSUE THREAD

**Issue by tjorim** [fanout/reconnecting-eventsource#12]
There was a new release (1.0.2) that hasn't been published on npm yet.
Latest version available is [1.0.1](https://www.npmjs.com/package/reconnecting-eventsource?activeTab=versions).

**Comment by gobengo** [comment]
Hi @tjorim. I just published 1.0.2 to npm. Thanks for the reminder. https://www.npmjs.com/package/reconnecting-eventsource/v/1.0.2

**Comment by tjorim** [comment]
Thanks!
