### ISSUE TITLE
How can we setup the retry interval

### ISSUE THREAD

**Issue by cw1427** [fanout/reconnecting-eventsource#13]
This project is useful, I just want to know is it possible to setup the retry interval during the max retry time. Like we could setup 1sec for every time retry connection.

**Comment by gobengo** [comment]
@cw1427 It looks like right now, whenever the EventSource disconnects, it waits (Math.random() * this.max_retry_time) before reconnecting.

Are you asking for a way to opt out of this randomness, and have it always wait exactly 1 second before reconnecting?

**Comment by cw1427** [comment]
Thanks @gobengo ,  Yes, it is what I want to know.  But the implement waists a random looks better.
Close this CR.
