### ISSUE TITLE
how to use the minified version in the browser?

### ISSUE THREAD

**Issue by becvert** [fanout/reconnecting-eventsource#15]
Hello,
In development, in the browser, I use the non-minified version, then I can call `new window.ReconnectingEventSource` just fine.
In production I'd like to use the minified version, but then `window.ReconnectingEventSource` is `undefined`.
What am I missing here?
Thank you

**Comment by gobengo** [comment]
@becvert You weren't missing anything. It was a legit bug in that minified build. Thanks for pointing it out!

I just fixed it in PR #16, then released v1.0.3 to npm. If you upgrade to v1.0.3, embedding the minified dist bundle should set `window.ReconnectingEventSource`.

Please let me know if it works for you.

**Comment by becvert** [comment]
It works!
Thank you very much
