### ISSUE TITLE
Cannot read property max_retry_time of undefined when configuration object undefined

### ISSUE THREAD

**Issue by aral** [fanout/reconnecting-eventsource#17]
It looks like the check for `max_retry_time` (https://github.com/fanout/reconnecting-eventsource/blob/master/src/reconnecting-eventsource.js#L33) is happening before the check for an undefined configuration object argument (https://github.com/fanout/reconnecting-eventsource/blob/master/src/reconnecting-eventsource.js#L35). This leads to the error _Cannot read property max_retry_time of undefined_ when the configuration object is undefined.

**Comment by jkarneges** [comment]
Thanks for the report! Fixed in 88791c56222bdf7ee416735f56b4609e7a5cbd5d
