### ISSUE TITLE
Change in the default export in lib?

### ISSUE THREAD

**Issue by joyheron** [fanout/reconnecting-eventsource#26]
I'm not exactly sure what the issue is, but when reconnecting-eventsource was upgraded from 1.0.3 to 1.0.4, I now get this message:

```
5: import ReconnectingEventSource from 'reconnecting-eventsource'
          ^
6: 
7: function komponenteAngepasst (event) {

🔗 visit https://rollupjs.org/guide/en/#error-name-is-not-exported-by-module for details
✗ assets/bundle.legacy.js: 'default' is not exported by node_modules/reconnecting-eventsource/lib/index.js
aborting: Error: 'default' is not exported by node_modules/reconnecting-eventsource/lib/index.js
```

I am using rollup with the faucet-pipeline as my bundler.

**Comment by joyheron** [comment]
It works for me when I use 

```import ReconnectingEventSource from 'reconnecting-eventsource/src/index'```

so I am doing this as a workaround for now.

**Comment by kevinswiber** [comment]
Hi @joyheron, can you share your rollup config?  This seems to work for me when I use the commonjs plugin.  https://github.com/rollup/rollup-plugin-commonjs

**Comment by kevinswiber** [comment]
Hey @joyheron, apologies.  I just saw that you're using faucet-pipeline.  You must be using `faucet-pipeline-esnext`.  In your faucet config, please set an exclusion for `reconnecting-eventsource`.

Example:

```js
module.exports = {
  js: [{
    source: './main.js',
    target: './bundle.js',
    esnext: {
      exclude: ["reconnecting-eventsource"]
    }
  }]
}
```

Hope this helps!

**Comment by joyheron** [comment]
Hi @kevinswiber! Thanks for the response.

This will work, but I guess I thought that the `main` entry in the package.json should point to the ES6 Modules before bundling so that I can use the sources directly and bundle them myself. However, I have tried to find documentation for this, but I can't find anything to that effect.

My current workaround is to just import the sources directly from `src` with

    import ReconnectingEventSource from 'reconnecting-eventsource/src/index'

**Comment by joyheron** [comment]
From my perspective, this ticket can be closed for this reason.

**Comment by kevinswiber** [comment]
@joyheron Thanks for looking into this!  The trouble comes in with supporting both ES6 and CommonJS use cases (and then doing so across multiple versions of Node.js).  The workaround you are using is a common one, though the developer experience is a bit unfortunate.
