### ISSUE TITLE
LastEventID

### ISSUE THREAD

**Issue by ImVexed** [fanout/reconnecting-eventsource#28]
From what I can see in the spec: https://html.spec.whatwg.org/multipage/server-sent-events.html#concept-event-stream-last-event-id

LastEventID should be set off of the most recent `id` field received on an event. NOT a literal field called `lastEventId` as seen on https://github.com/fanout/reconnecting-eventsource/blob/master/src/reconnecting-eventsource.js#L104

**Comment by harmony7** [comment]
I've reviewed this and it seems the current implementation is correct.

The data stream from the endpoint will provide blocks containing a field named `id`.  When stream processing encounters this value, the processor makes a note of it (sets the "last event ID" to this value).  This all happens inside the stream processing inside the browser and is completely outside the realm of this library.

When the browser eventually dispatches this as an event, it follows these steps (from the linked spec document, emphasis mine):

> For web browsers, the appropriate steps to dispatch the event are as follows:
> 
> 1. Set the last event ID string of the event source to the value of the last event ID buffer. The buffer does not get reset, so the last event ID string of the event source remains set to this value until the next time it is set by the server.
> 
> ...
> 5. Initialize event's `type` attribute to `message`, ... and **its `lastEventId` attribute to the last event ID string** of the event source.
> 
> ...
> 8. Queue a task which, if the `readyState` attribute is set to a value other than `CLOSED`, dispatches the newly created event at the `EventSource` object.

By the time the line you specified is executed, the `event` object we receive is already set up described in step 5 in the list above, so we read it from the `lastEventId` field.

The confusion seems to come from the fact that even though the endpoint provides a stream with a field named `id`, by the time this reaches the API on the `event` object passed to `onmessage`, it is made available using a field named `lastEventId`.
