### ISSUE TITLE
events for onmessage is not properly forwarded

### ISSUE THREAD

**Issue by dhubler** [fanout/reconnecting-eventsource#35]
Example: This does not work
        const events = new ReconnectingEventSource(myUrl,
            { max_retry_time: 120000 }
        );
        events.onmessage(() => {
            console.log("NEVER GETS HERE");
        });

Workaround, this does work
        const events = new ReconnectingEventSource(myUrl,
            { max_retry_time: 120000 }
        );
        events.addEventListener("message", () => {
            console.log("GOT HERE");
        });

Problem:
  I think the onmessage empty stub is called, not the overridden one because of early binding of function scope (IFFE)

Env:
  Chrome 88/Linux, Webpack

**Comment by harmony7** [comment]
Hi there,

The way you are using the API is incorrect.  

```JavaScript
const events = new ReconnectingEventSource(myUrl,
   { max_retry_time: 120000 }
);
events.onmessage = () => {
   console.log("THIS WILL GET CALLED");
};
```

This is just like if you were listening for `window`'s `load` event
(if you're familiar with the HTML DOM API), you would either write:

```JavaScript
window.onload = () => {
    console.log("window load event");
};
```
or
```
```


See https://www.w3.org/TR/eventsource/#server-sent-events-intro
