### ISSUE TITLE
Can remove a line

### ISSUE THREAD

**Issue by david-mark** [fanout/reconnecting-eventsource#48]
Inside _onerror:

this._eventSource.close();

...appears to do nothing, as the first line of the eventSource._close() method just returns immediately (and silently) if readyState is 2 (CLOSED). There's definitely some lousy code in the original module; I remember tearing my hair out trying to follow what it was doing with the error events (to solve the same problem you are dealing with here).

From the original:

EventSource.prototype.close = function () {
  this._close()
}

this._close = function () {
    if (readyState === EventSource.CLOSED) return
    readyState = EventSource.CLOSED
    if (req.abort) req.abort()
    if (req.xhr && req.xhr.abort) req.xhr.abort()
  }

**Comment by david-mark** [comment]
In addition, what is the line above that sets readyState to 1 (OPEN) if it is 0 (CONNECTING)? Is this working around some shortcoming in the original? Seems like an odd thing to do and the original is so full of silent failures that I'm about ready to throw it away and write my own. :(

**Comment by harmony7** [comment]
Hi there,

Yes, it does appear that `close()` would effectively result in a no-op by the way `EventSource/eventsource` implements it.

Keep in mind however that reconnecting-eventsource is a wrapper around `EventSource` as provided by the DOM (native code). `EventSource/eventsource` is a polyfill, and the behavior that you are describing is just how that polyfill happens to implement `close()`.

I believe we are doing the right thing by calling `close()` on the old object before creating a new one in response to an error. Closing for now, but feel free to reopen if you have further comments/thoughts.
