### ISSUE TITLE
Vite exception in production builds (TypeError: YW is not a constructor)

### ISSUE THREAD

**Issue by mandray** [fanout/reconnecting-eventsource#61]
Similar to this issue: https://github.com/fanout/reconnecting-eventsource/issues/56

In development there aren't any issues, but in the production version using Vite it does not build correctly

Using reconnecting-eventsource 1.4.0

The error is 
```
 TypeError: YW is not a constructor
```

**Comment by harmony7** [comment]
thanks for the report, I'm looking into this
