### ISSUE TITLE
onmessage handler calls twice

### ISSUE THREAD

**Issue by NickShcherba** [fanout/reconnecting-eventsource#65]
There is a bug in 1.5.0 version.

Code to reproduce: 
`
const es = ReconnectingEventSource(url, configuration);
es.onmessage = (e => console.log(e))
`
This error comes from this code. 

        this._listeners = {
            open: [],
            error: [],
            message: [],
        };
        this._eventSource.onmessage = (event) => { this.onmessage(event); };
        for (const type of Object.keys(this._listeners)) {
            this._eventSource.addEventListener(type, this._onevent_wrapped);
        }

Subscription to 'message' happens twice. Because  `_listeners` has an entry for a message. In the previous version `_listeners` was an empty object.

This issue can be reproduced if someone adds an event listener with an `open`, `error`, or `message` name.

**Comment by harmony7** [comment]
Thanks for filing this, I'll take a look

**Comment by harmony7** [comment]
Thanks for the catch, I've published 1.5.1 that should fix this.
