### ISSUE TITLE
TypeError: ReconnectingEventSource is not a constructor

### ISSUE THREAD

**Issue by imleaver** [fanout/reconnecting-eventsource#68]
Hi there,

I follow exactly the instruction in readme

replace new EventSource to new ReconnectingEventSource

But it came out `TypeError: ReconnectingEventSource is not a constructor`

My code as below
`import EventSource from 'eventsource';
import ReconnectingEventSource from "reconnecting-eventsource";
let source = new ReconnectingEventSource('https://url.com');
source.onmessage = function(e) {}`

NodeJS version: v16.18.0

**Comment by harmony7** [comment]
Hi, thanks for your patience.
Today, I've published v1.6.1 that should fix this.

Please give it a go.

**Comment by toptensoftware** [comment]
I'm seeing a similar issue to this.  Importing into a vue3 application.  The app runs find in development mode but if build it (npm run build) I get a "<uglifiedsymbol>" is not a constructor.

package.json:
```
    "reconnecting-eventsource": "^1.6.2",
```

importing like so:
```
import ReconnectingEventSource from "reconnecting-eventsource"
```

constructing:
```
let eventsSource = new ReconnectingEventSource('/api/events');
```

**Comment by toptensoftware** [comment]
As an experiment I hacked `node_modules/reconnecting-eventsource/package.json` and changed

```
 "main": "lib/index.js"
```

to

```
  "main": "src/index.js"
```

Seems like the packager (vite/rollup) is packaging the already minified version and something's getting confused.

**Comment by harmony7** [comment]
@toptensoftware looks like that package.json is from a version before 1.5.0?  Can you try updating to 1.6.1 or newer and giving it another go?

In 1.6.2, it should look like this:

```
  "main": "./build/src/reconnecting-eventsource.js",
   "exports": {
    ".": {
      "types": "./build/src/reconnecting-eventsource.d.ts",
      "import": "./build/esm/reconnecting-eventsource.js",
      "require": "./build/src/reconnecting-eventsource.js"
    }
  },
  "module": "./build/esm/reconnecting-eventsource.js",
  "esnext": "./build/esnext/reconnecting-eventsource.js",
  "types": "./build/src/reconnecting-eventsource.d.ts",
```

**Comment by toptensoftware** [comment]
Ah, you're right of course.  I did check the version before posting but checked in the wrong project - my bad.

Thanks for this super handy package.
